# Generated by Django 5.0.7 on 2026-07-21 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampling_date', models.DateField(verbose_name='Datum uzorkovanja')),
                ('age_at_test', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='Dob u trenutku nalaza')),
                ('gender_at_test', models.CharField(blank=True, choices=[('female', 'Ženski'), ('male', 'Muški'), ('other', 'Drugo / ne želim navesti')], editable=False, max_length=10, verbose_name='Spol u trenutku nalaza')),
                ('input_method', models.CharField(choices=[('manual', 'Ručni unos'), ('pdf', 'PDF dokument')], default='manual', max_length=10, verbose_name='Način unosa')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='blood_tests/%Y/%m/', verbose_name='Izvorni dokument')),
                ('processing_status', models.CharField(choices=[('draft', 'Skica'), ('pending_review', 'Čeka provjeru'), ('completed', 'Dovršeno'), ('failed', 'Neuspjela obrada')], default='draft', max_length=20, verbose_name='Status obrade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum unosa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zadnja izmjena')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_tests', to=settings.AUTH_USER_MODEL, verbose_name='Korisnik')),
            ],
            options={
                'verbose_name': 'Krvni nalaz',
                'verbose_name_plural': 'Krvni nalazi',
                'ordering': ('-sampling_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='BloodTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_code', models.CharField(max_length=50, verbose_name='Šifra parametra')),
                ('parameter_name', models.CharField(max_length=150, verbose_name='Naziv parametra')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Brojčana vrijednost')),
                ('text_value', models.CharField(blank=True, max_length=255, verbose_name='Tekstualna vrijednost')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Mjerna jedinica')),
                ('reference_min', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Donja referentna granica')),
                ('reference_max', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True, verbose_name='Gornja referentna granica')),
                ('reference_text', models.CharField(blank=True, max_length=255, verbose_name='Referentni interval')),
                ('status', models.CharField(choices=[('low', 'Sniženo'), ('normal', 'Uredno'), ('high', 'Povišeno'), ('unknown', 'Nepoznato')], default='unknown', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum stvaranja')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zadnja izmjena')),
                ('blood_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.bloodtest', verbose_name='Krvni nalaz')),
            ],
            options={
                'verbose_name': 'Rezultat krvnog nalaza',
                'verbose_name_plural': 'Rezultati krvnih nalaza',
                'ordering': ('parameter_name',),
            },
        ),
        migrations.AddIndex(
            model_name='bloodtest',
            index=models.Index(fields=['user', '-sampling_date'], name='bloodtest_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodtestresult',
            index=models.Index(fields=['parameter_code'], name='bloodresult_param_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodtestresult',
            index=models.Index(fields=['status'], name='bloodresult_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='bloodtestresult',
            constraint=models.UniqueConstraint(fields=('blood_test', 'parameter_code'), name='unique_parameter_per_blood_test'),
        ),
        migrations.AddConstraint(
            model_name='bloodtestresult',
            constraint=models.CheckConstraint(check=models.Q(('numeric_value__isnull', False), models.Q(('text_value', ''), _negated=True), _connector='OR'), name='blood_result_has_value'),
        ),
    ]
